@startuml architecture
' skinparam linetype ortho

node "Frontend" {
  component Client [
    Frontend
    Svelte TS
  ]
}

node "Backend" {
  component API [
    API
    NestJS
  ]

  [API] -- [PostgreSQL]
}

Client -- [API]

@enduml